import { Navbar, Sidebar } from "@/components/layout";
import { PositionProvider } from "@/context/PositionContext";
import { cookies } from "next/headers";
import { getActivePositionId } from "../actions/position/getActivePosition";
import { AuthProvider } from "@/context/authContext";
import iranYekanFont from "@/constans/LocalFont";
import { GetMe } from "../actions/user/getMe";
import "../globals.css"

export default async function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const meUser = await GetMe();
  const cookieStore = await cookies()
  const userCookie = cookieStore.get("user")
  const user = userCookie ? JSON.parse(userCookie.value) : null
  const activePositionId = await getActivePositionId()

  return (
    <html lang="fa" dir="rtl">
      <body className={`${iranYekanFont.variable} antialiased`}>
        <AuthProvider initialUser={meUser.user}>
          <PositionProvider initialActiveId={activePositionId} initialPositions={user?.position || []}>
            <div className="min-h-screen bg-slate-900 text-white font-sans" dir="rtl">
              <div className="flex">
                {/* Sidebar - Fixed on right side */}
                <div className="fixed top-0 right-0 h-screen z-20">
                  <Sidebar />
                </div>

                {/* Main Content Area */}
                <div className="flex-1 flex flex-col lg:mr-72 min-h-screen" dir="ltr">
                  <div dir="rtl">
                    {/* Navbar - Sticky */}
                    <Navbar />

                    {/* Page Content */}
                    <main className="flex-1 p-6 overflow-auto bg-slate-900">
                      <div className="mx-auto">
                        {children}
                      </div>
                    </main>
                  </div>
                </div>
              </div>
            </div>
          </PositionProvider>
        </AuthProvider>

      </body>
    </html>

  );
}


// import type { Metadata } from "next";
// import "./globals.css";
// import iranYekanFont from "@/constans/LocalFont";
// import { Toaster } from "react-hot-toast";
// import { AuthProvider } from "@/context/authContext";
// import { GetMe } from "./actions/user/getMe";
// import { PositionProvider } from "@/context/PositionContext";
// import { cookies } from "next/headers";
// import { getActivePositionId } from "./actions/position/getActivePosition";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const dynamic = "force-dynamic";


// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
// const meUser = await GetMe();

// const cookieStore = await cookies()
// const userCookie = cookieStore.get("user")
// const user = userCookie ? JSON.parse(userCookie.value) : null
// const activePositionId = await getActivePositionId()

// return children
// <html lang="fa" dir="rtl">
//   <body className={`${iranYekanFont.variable} antialiased`}>
//     <AuthProvider initialUser={meUser.user}>
//       <PositionProvider initialActiveId={activePositionId} initialPositions={user?.position || []}>
//         {children}
//         <Toaster position="top-center" reverseOrder={false} />
//       </PositionProvider>
//     </AuthProvider>
//   </body>
// </html>
// }
